#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts /tmp/hosts_tmp
sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2\tlocalhost/' /tmp/hosts_tmp
if grep -q 'facebook\.com' /tmp/hosts_tmp; then
    sed -i 's/.*facebook\.com.*/8.8.8.8\tfacebook.com/' /tmp/hosts_tmp
else
    echo '8.8.8.8	facebook.com' >> /tmp/hosts_tmp
fi
cp /tmp/hosts_tmp /etc/hosts
